/** Arco 图标映射 - 将字符串图标名映射到实际组件 */
import {
  IconApps,
  IconSearch,
  IconFile,
  IconMessage,
  IconCalendar,
  IconCloud,
  IconHome,
  IconLocation,
  IconLink,
  IconStorage,
  IconTool,
  IconEmpty,
  IconSend,
  IconCopy,
  IconDelete,
  IconSettings,
  IconPlus,
  IconClose,
  IconBook,
  IconAttachment,
  IconCode,
  IconClockCircle,
  IconMenuUnfold,
  IconMenuFold,
  IconRefresh,
  IconUser,
  IconArrowLeft,
  IconUpload,
  IconBulb,
  IconExclamationCircleFill,
  IconBug,
} from '@arco-design/web-vue/es/icon'

/** 图标名字符串到组件的映射表 */
export const iconMap: Record<string, any> = {
  'icon-apps': IconApps,
  'icon-search': IconSearch,
  'icon-file': IconFile,
  'icon-mail': IconMessage,
  'icon-calendar': IconCalendar,
  'icon-cloud': IconCloud,
  'icon-home': IconHome,
  'icon-location': IconLocation,
  'icon-link': IconLink,
  'icon-storage': IconStorage,
  'icon-tool': IconTool,
  'icon-empty': IconEmpty,
  'icon-send': IconSend,
  'icon-copy': IconCopy,
  'icon-delete': IconDelete,
  'icon-settings': IconSettings,
  'icon-plus': IconPlus,
  'icon-close': IconClose,
  'icon-book': IconBook,
  'icon-attachment': IconAttachment,
  'icon-code': IconCode,
  'icon-clock-circle': IconClockCircle,
  'icon-menu-unfold': IconMenuUnfold,
  'icon-menu-fold': IconMenuFold,
  'icon-refresh': IconRefresh,
  'icon-user': IconUser,
  'icon-left-arrow': IconArrowLeft,
  'icon-arrow-left': IconArrowLeft,
  'icon-cloud-upload': IconUpload,
  'icon-upload': IconUpload,
  'icon-stock': IconBulb,
  'icon-bulb': IconBulb,
  'icon-exclamation-circle-fill': IconExclamationCircleFill,
  'icon-bug': IconBug,
}

/** 根据字符串名获取图标组件 */
export function getIcon(name: string): any {
  return iconMap[name] || IconApps
}
